package com.ums.upos.uapi.emv;

public class EmvTermCfgConstrants {
	public final static String TERMCAP = "termCap";
	public final static String ADDTERMCAP = "additionalTermCap";
	public final static String IFDSEQNO = "IFDSerialNum";
	public final static String COUNTRYCODE = "countryCode";
	public final static String TERMID = "termId";
	public final static String TERMTYPE = "termType";
	public final static String CURRENCYCODE = "curCode";
	public final static String PSE = "pse";
	public final static String CARDHOLDERCONFIRM = "cardHolderConfirm";
	public final static String PREFEREDORDER = "preferedOrder";
	public final static String PARTIALAID = "partialAID";
	public final static String MULLANGUAGE = "mulLanguage";
	public final static String COMMONCHARSET = "CommonCharset";
	public final static String IPKCVALIDTIONCHECK = "IpKCVValidtionCheck";
	public final static String CONTAINDEFAULTDDOL = "containDefaultDDOL";
	public final static String CAPKFAILOPERACTION = "CAPKFailOperAction";
	public final static String CAPKCHECKSUM = "CAPKChecksum";
	public final static String BYPASSPIN = "BypassPIN";
	public final static String GETDATAFORPINCOUNTER = "GetDataForPINCounter";
	public final static String AMOUNTBEFORECVM = "amountBeforeCVM";
	public final static String LIMITFLOORCHECK = "limitFloorCheck";
	public final static String RANDOMTRANSSELECT = "randomTransSel";
	public final static String VALOCITYCHECK = "velocityCheck";
	public final static String WRITETRANSLOG = "transLog";
	public final static String EXCEPTIONFILE = "exceptionFile";
	public final static String TRMBASEONAIP = "trmBaseOnAIP";
	public final static String TERMACTCODE = "terminalActionCode";
	public final static String DEFACTCODEAFTER1STGENAC = "defActCodesAfter1stGenAC";
	public final static String FORCEONLINE = "forceOnline";
	public final static String FORCEACCEPT = "forceAccept";
	public final static String ADVICES = "advices";
	public final static String IISVOICEREFERA = "IISVoiceReferal";
	public final static String CARDVOICEREFERAL = "CardVoiceReferal";
	public final static String BATCHDATACAPTURE = "BatchDataCapture";
	public final static String DEFAULTTDOL = "DefaultTDOL";
	public final static String ENTRYMODEUSINGMAGSTRIPE = "EntryModeUsingMagStripe";
	public final static String ACCOUNTSELECT = "AccountSelect";
}
